# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        cache: ~
        member_photo_desktop:
            jpeg_quality: 85
            png_compression_level: 8
            filters:
                thumbnail:
                    size: [50, 50]