liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: resized_images

  filter_sets:
    cache: ~
    member_photo_desktop:
      jpeg_quality:          85
      png_compression_level: 8
      filters:
        thumbnail:
          size:          [360, 360]

