vich_uploader:
  db_driver: orm

  mappings:
    member_images:
      uri_prefix:         '%app.path.member_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.member_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above

    customer_images:
      uri_prefix: '%app.path.customer_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.customer_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above

    media_images:
      uri_prefix: '%app.path.media_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.media_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above