vich_uploader:
  db_driver: orm

  mappings:
    member_images:
      uri_prefix:         '%app.path.member_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.member_images%'
      namer:
        service: Vich\UploaderBundle\Naming\HashNamer
        options: { algorithm: 'sha256', length: 15 }

    customer_images:
      uri_prefix: '%app.path.customer_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.customer_images%'
      namer:
        service: Vich\UploaderBundle\Naming\HashNamer
        options: { algorithm: 'sha256', length: 15 }

    media_images:
      uri_prefix: '%app.path.media_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.media_images%'
      namer:
        service: Vich\UploaderBundle\Naming\HashNamer
        options: { algorithm: 'sha256', length: 15 }
