vich_uploader:
    db_driver: orm

    mappings:
        member_image:
            uri_prefix: '%app.path.member_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.member_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
