#vich_uploader:
#    db_driver: orm
#
#    mappings:
#        products:
#            uri_prefix: /images/products
#            upload_destination: '%kernel.project_dir%/public/images/products'

vich_uploader:
    db_driver: orm

    mappings:
        member_images:
            uri_prefix: '%app.path.member_images%'
            upload_destination: '%kernel.project_dir%/public/app.path.member_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer