index:
  path: /
  controller: App\Controller\DefaultController::index

contact:
  path:
    fr: /nous-contacter
    en: /contact-us
  controller: App\Controller\DefaultController::contact

page:
  path:
    en: /{slug}
    fr: /{slug}
  controller: App\Controller\DefaultController::page
  requirements:
    slug: '^(?!admin).+'
    #slug ne commençant PAS par admin. Donc si le slug ne commence pas par admin ALORS le point,
    # il faut n'importe quel caractère au moins 1 fois

