index:
  path: /
  controller: App\Controller\DefaultController::index

contact:
  path:
    fr: /nous-contacter
    en: /contact-us
  controller: App\Controller\DefaultController::contact
  default:
    name: ''

page:
  path:
    fr: /{slug}
    en: /{slug}
    controller: App\Controller\DefaultController::page
    requirements:
      slug: '^(?!admin).+'