app_dashboard:
    prefix: "/admin"
    resource: "routes/dashboard.yaml"
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#page2:
#    path: /page2
#    controller: App\Controller\DefaultController::page2

#app_front:
#    resource: "routes/front.yaml"