front:
    resource: 'routes/front.yaml'
    prefix:
        fr: '/'
        en: '/en/'

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

app_dashboard:
    prefix: "/admin"
    resource: "routes/dashboard.yaml"
