app_security:
    resource: "routes/security.yaml"

app_front: 
    prefix: "/"
    resource: "routes/front.yaml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

app_dashboard:
    prefix: "/admin"
    resource: "routes/dashboard.yaml"

front: 
    resource: 'routes/front.yaml'
    prefix:
        fr: '/'
        en: '/en'